title: Denis Gorshkov CV
description: Full-stack developer
baseurl: ""
url: https://leenday.github.io/cv/

theme: cvless

# site settings
taglong: Full-stack developer(Ruby/Elixir/React)
tagshort: Full-stack dev

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  linkedin: leenday
  github: leenday

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
